# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:17
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
